name: pull-request

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check node version
        run: node --version
      - name: Install dependencies
        # There's a bug in yarn 2 where checksums for packages built from a
        # github repo have differing checksums depending on which platform
        # they're built.
        # See: https://github.com/yarnpkg/berry/issues/2399 for more info.
        run: YARN_CHECKSUM_BEHAVIOR=update yarn install --immutable
      - name: Run tests
        run: yarn run test
