name: pull-request

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check node version
        run: node --version
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn run test
